#ASSIGNMENT=wp1p1
#ASSIGNMENT=wp1
#ASSIGNMENT=wp2
#ASSIGNMENT=wp3
ASSIGNMENT=project
TEAM_MEMBERS_CSV="Atif Iqbal Ahangar (NETID:aahangar, ID:111416569), Vishal Jasrotia (NETID:jvishal, ID:111578708)"
# list space-separated completed components: cooperative preemptive signals swap filesystem network multicore
PROJECT_PARTS=cooperative signals
PROJECT_POINTS=50
